package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/grokify/gogithub/profile"
	"github.com/spf13/cobra"
)

var (
	statsReportInputDir     string
	statsReportOutputJSON   string
	statsReportOutputMD     string
	statsReportOutputHTML   string
	statsReportOutputText   string
	statsReportTitle        string
	statsReportShowDetails  bool
	statsReportDataURL      string
	statsReportRegenerateCmd string
)

var statsReportCmd = &cobra.Command{
	Use:   "stats-report",
	Short: "Generate aggregated statistics report from monthly files",
	Long: `Generate a hierarchical statistics report from monthly JSON files.

This command reads individual monthly JSON files (generated by --output-monthly-dir)
and aggregates them into a structured report with:
  - Annual totals
  - Quarterly breakdowns
  - Monthly details

The report can be output in multiple formats:
  - JSON: Machine-readable hierarchical data structure
  - Markdown: Human-readable documentation format
  - HTML: Web-ready report with styling
  - Text: Plain text for terminal display

Examples:
  # Generate JSON report from monthly files
  gogithub stats-report --input-dir ./stats/ --output-json report.json

  # Generate Markdown report
  gogithub stats-report --input-dir ./stats/ --output-md README.md

  # Generate multiple formats at once
  gogithub stats-report --input-dir ./stats/ \
    --output-json report.json \
    --output-md README.md \
    --output-html report.html

  # Customize the report
  gogithub stats-report --input-dir ./stats/ \
    --output-md README.md \
    --title "My GitHub Stats" \
    --show-details=false

  # Include regeneration command in output
  gogithub stats-report --input-dir ./stats/ \
    --output-md README.md \
    --regenerate-cmd "gogithub profile --user myuser --from 2024-01-01 --to 2024-03-31 --visibility public --output-monthly-dir ./stats/"

Input files:
  Expects JSON files in the format produced by --output-monthly-dir.
  Files should contain the monthly output structure with metadata and stats.`,
	RunE: runStatsReport,
}

func init() {
	statsReportCmd.Flags().StringVarP(&statsReportInputDir, "input-dir", "i", "", "Directory containing monthly JSON files (required)")
	statsReportCmd.Flags().StringVar(&statsReportOutputJSON, "output-json", "", "Output JSON report file")
	statsReportCmd.Flags().StringVar(&statsReportOutputMD, "output-md", "", "Output Markdown report file")
	statsReportCmd.Flags().StringVar(&statsReportOutputHTML, "output-html", "", "Output HTML report file")
	statsReportCmd.Flags().StringVar(&statsReportOutputText, "output-text", "", "Output plain text report file")
	statsReportCmd.Flags().StringVar(&statsReportTitle, "title", "", "Custom title for the report")
	statsReportCmd.Flags().BoolVar(&statsReportShowDetails, "show-details", true, "Include monthly detail sections")
	statsReportCmd.Flags().StringVar(&statsReportDataURL, "data-url", "https://github.com/grokify/gogithub", "URL for data source attribution")
	statsReportCmd.Flags().StringVar(&statsReportRegenerateCmd, "regenerate-cmd", "", "Command to regenerate the data (shown in output)")

	if err := statsReportCmd.MarkFlagRequired("input-dir"); err != nil {
		panic(err)
	}
}

func runStatsReport(cmd *cobra.Command, args []string) error {
	// Validate input directory
	info, err := os.Stat(statsReportInputDir)
	if err != nil {
		return fmt.Errorf("input directory: %w", err)
	}
	if !info.IsDir() {
		return fmt.Errorf("input path is not a directory: %s", statsReportInputDir)
	}

	// Check that at least one output is specified
	if statsReportOutputJSON == "" && statsReportOutputMD == "" && statsReportOutputHTML == "" && statsReportOutputText == "" {
		return fmt.Errorf("at least one output format is required: --output-json, --output-md, --output-html, or --output-text")
	}

	// Load monthly files
	fmt.Fprintf(os.Stderr, "Loading monthly files from %s...\n", statsReportInputDir)
	files, err := profile.LoadMonthlyFiles(statsReportInputDir)
	if err != nil {
		return fmt.Errorf("load monthly files: %w", err)
	}
	fmt.Fprintf(os.Stderr, "Found %d monthly files\n", len(files))

	// Build report
	report, err := profile.BuildStatsReport(files)
	if err != nil {
		return fmt.Errorf("build stats report: %w", err)
	}

	// Build raw data file list for markdown
	var rawDataFiles []string
	for _, f := range files {
		filename := fmt.Sprintf("%s_github_%s_%04d-%02d.json",
			f.Username,
			f.Metadata.Visibility,
			f.Year,
			f.Month)
		rawDataFiles = append(rawDataFiles, filename)
	}

	// Build render options
	renderOpts := profile.RenderOptions{
		Title:            statsReportTitle,
		ShowMonthDetails: statsReportShowDetails,
		ShowDataSource:   true,
		DataSourceURL:    statsReportDataURL,
		RawDataFiles:     rawDataFiles,
		RegenerateCmd:    statsReportRegenerateCmd,
	}

	// Generate outputs
	if statsReportOutputJSON != "" {
		if err := profile.WriteStatsReport(statsReportOutputJSON, report); err != nil {
			return fmt.Errorf("write JSON report: %w", err)
		}
		fmt.Fprintf(os.Stderr, "Wrote %s\n", statsReportOutputJSON)
	}

	if statsReportOutputMD != "" {
		renderOpts.Format = profile.RenderFormatMarkdown
		if err := profile.RenderToFile(statsReportOutputMD, report, renderOpts); err != nil {
			return fmt.Errorf("write Markdown report: %w", err)
		}
		fmt.Fprintf(os.Stderr, "Wrote %s\n", statsReportOutputMD)
	}

	if statsReportOutputHTML != "" {
		renderOpts.Format = profile.RenderFormatHTML
		if err := profile.RenderToFile(statsReportOutputHTML, report, renderOpts); err != nil {
			return fmt.Errorf("write HTML report: %w", err)
		}
		fmt.Fprintf(os.Stderr, "Wrote %s\n", statsReportOutputHTML)
	}

	if statsReportOutputText != "" {
		renderOpts.Format = profile.RenderFormatText
		if err := profile.RenderToFile(statsReportOutputText, report, renderOpts); err != nil {
			return fmt.Errorf("write text report: %w", err)
		}
		fmt.Fprintf(os.Stderr, "Wrote %s\n", statsReportOutputText)
	}

	// Print summary
	total := report.TotalStats()
	fmt.Fprintf(os.Stderr, "\nReport Summary:\n")
	fmt.Fprintf(os.Stderr, "  User: %s\n", report.Metadata.Username)
	fmt.Fprintf(os.Stderr, "  Period: %s to %s\n", report.Metadata.DataRange.From, report.Metadata.DataRange.To)
	fmt.Fprintf(os.Stderr, "  Years: %d\n", len(report.Years))
	totalQuarters := 0
	totalMonths := 0
	for _, y := range report.Years {
		totalQuarters += len(y.Quarters)
		for _, q := range y.Quarters {
			totalMonths += len(q.Months)
		}
	}
	fmt.Fprintf(os.Stderr, "  Quarters: %d\n", totalQuarters)
	fmt.Fprintf(os.Stderr, "  Months: %d\n", totalMonths)
	fmt.Fprintf(os.Stderr, "  Total commits: %d\n", total.Commits)
	fmt.Fprintf(os.Stderr, "  Total releases: %d\n", total.Releases)
	fmt.Fprintf(os.Stderr, "  Net additions: %+d\n", total.NetAdditions)

	return nil
}

// listRawDataFiles returns the filenames of monthly JSON files in a directory.
func listRawDataFiles(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}

	var files []string
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		name := entry.Name()
		if strings.HasSuffix(name, ".json") && strings.Contains(name, "_github_") {
			files = append(files, name)
		}
	}

	return files, nil
}

// resolveOutputPath resolves an output path relative to input directory if not absolute.
func resolveOutputPath(outputPath, inputDir string) string {
	if filepath.IsAbs(outputPath) {
		return outputPath
	}
	return filepath.Join(inputDir, outputPath)
}
